version: "3.9"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    container_name: mc
    environment:
      - TYPE=PAPER
      - EULA=TRUE
      - VERSION=1.18.1
    volumes:
      - ./mc:/data
    networks:
      - reciper_net

networks:
  reciper_net:
    name: reciper_network
